#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
微信机器人独立进程
- 通过 mabowx 公开 API 与微信交互
- 通过Flask提供API与主应用通信
"""

import logging
import threading
import requests
import time
import json
import uuid
from datetime import datetime
from flask import Flask, request, jsonify
from dotenv import load_dotenv
from mabowx import MediaFileMismatchError, MediaIdentityError, WeChat, media_download_trace
import comtypes
import sys
import os
from pathlib import Path

# 本机内部 API 调用必须绕过系统代理。
# Windows/Sparkle/Mihomo 环境里常有 HTTP_PROXY=127.0.0.1:7890；
# 如果该代理未运行，requests 会把本机 Web 请求也错误送进代理，
# 导致 wx_bot 收到消息但无法转发给主应用，summary_plus 等插件不会触发。
def _ensure_localhost_bypasses_proxy() -> None:
    local_hosts = ["127.0.0.1", "localhost", "::1"]
    for key in ("NO_PROXY", "no_proxy"):
        existing = os.environ.get(key, "")
        parts = [p.strip() for p in existing.split(",") if p.strip()]
        lower = {p.lower() for p in parts}
        changed = False
        for host in local_hosts:
            if host.lower() not in lower:
                parts.append(host)
                changed = True
        if changed or not existing:
            os.environ[key] = ",".join(parts)


load_dotenv()
_ensure_localhost_bypasses_proxy()

def _bounded_env_int(name: str, default: int, minimum: int) -> int:
    try:
        return max(int(minimum), int(os.getenv(name, str(default))))
    except (TypeError, ValueError):
        return int(default)


# 添加项目根目录到Python路径，以便导入配置工具
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app.models.base import SessionLocal
from app.models.user_permission import WeChatUser
from app.services.wechat_file_store import (
    extract_file_name_from_message,
    get_wechat_file_store,
    looks_like_file_quote,
    sha256_file,
)
from app.utils.inflight_deduplicator import InFlightDeduplicator
from app.utils.health_state import OnlineProbeTracker
from app.utils.logging_utils import create_rotating_file_handler
from app.utils.wechat_media import image_file_fingerprint

# --- 全局变量 ---
wx = None
app = Flask(__name__)
restart_requested = False  # 重启请求标志
wechat_thread = None  # 微信线程引用

# 消息缓存：保存最近的消息对象以支持按需下载
# 格式: {chat_name: {message_id: msg_obj}}
message_cache = {}
message_cache_lock = threading.RLock()
CACHE_MAX_SIZE = 100  # 每个聊天最多缓存100条消息

# HTTP 客户端超时不会中止已经开始的库操作。相同请求共享一次
# 下载并短暂缓存成功路径；UI 事务和消息绑定由 mabowx 负责。
media_download_deduplicator = InFlightDeduplicator(
    ttl_seconds=120,
    wait_timeout_seconds=120,
)
# A request id is generated by the main app for every text part. If an HTTP
# caller repeats the same request after losing the response, share/cache the
# original result instead of touching the WeChat UI twice.
outbound_text_deduplicator = InFlightDeduplicator(
    ttl_seconds=300,
    wait_timeout_seconds=60,
)

# 群昵称自动校准属于应用调度；实际 UI 读取由 mabowx 公共 API 完成。
_bot_nickname_probe_lock = threading.RLock()
_bot_nickname_probe_next_at: dict[str, float] = {}
_bot_nickname_probe_running: set[str] = set()
_BOT_NICKNAME_CONFIRM_INTERVAL_SEC = 24 * 60 * 60
_BOT_NICKNAME_FAILURE_RETRY_SEC = 60 * 60
_BOT_NICKNAME_DISABLED_RECHECK_SEC = 5 * 60

# 这里只保护全局客户端引用的发布/销毁；mabowx 自己负责所有 UI 事务锁。
wx_client_lock = threading.RLock()

# 期望保持监听的聊天列表。通过 /api/remove_listener 移除的聊天会从这里删除，
# 这样可以区分“主动暂停监听”和“监听窗口异常关闭”。
desired_listeners: dict = {}
desired_listeners_lock = threading.RLock()
ONLINE_PROBE_INTERVAL_SEC = 5
ONLINE_PROBE_FAILURE_THRESHOLD = 3
ONLINE_PROBE_RECOVERY_THRESHOLD = 2
online_probe_tracker = OnlineProbeTracker(
    initial_online=False,
    failure_threshold=ONLINE_PROBE_FAILURE_THRESHOLD,
    recovery_threshold=ONLINE_PROBE_RECOVERY_THRESHOLD,
)
wechat_service_instance_id = uuid.uuid4().hex
wechat_connection_generation = 0
last_wechat_online = False
last_wechat_online_checked_at: float = 0.0
def _sync_online_probe_legacy_fields(snapshot: dict) -> dict:
    """Keep legacy globals coherent while callers migrate to probe metadata."""
    global last_wechat_online, last_wechat_online_checked_at
    last_wechat_online = bool(snapshot.get("online"))
    checked_at = snapshot.get("checked_at")
    if checked_at:
        last_wechat_online_checked_at = float(checked_at)
    return snapshot


def _online_probe_snapshot() -> dict:
    return _sync_online_probe_legacy_fields(online_probe_tracker.snapshot())


def _online_probe_mark_connected() -> dict:
    return _sync_online_probe_legacy_fields(
        online_probe_tracker.mark_connected(source="client_initialized")
    )


def _online_probe_mark_disconnected(reason: str) -> dict:
    return _sync_online_probe_legacy_fields(
        online_probe_tracker.mark_disconnected(reason)
    )


def _online_probe_record_result(online: bool, duration_ms: float) -> dict:
    return _sync_online_probe_legacy_fields(
        online_probe_tracker.record_result(
            online,
            duration_ms=duration_ms,
            source="connection_supervisor",
        )
    )


def _online_probe_record_error(error: object, duration_ms: float) -> dict:
    return _sync_online_probe_legacy_fields(
        online_probe_tracker.record_error(
            error,
            duration_ms=duration_ms,
            source="connection_supervisor",
        )
    )


def _parse_sender_blacklist(raw_value) -> list[str]:
    if not raw_value:
        return []
    try:
        parsed = json.loads(raw_value) if isinstance(raw_value, str) else raw_value
    except Exception:
        parsed = str(raw_value).splitlines()
    if not isinstance(parsed, list):
        return []
    return [str(item or "").strip() for item in parsed if str(item or "").strip()]


def _is_sender_blacklisted_for_chat(chat_name: str, sender: str) -> bool:
    if not chat_name or not sender:
        return False
    db = SessionLocal()
    try:
        user = db.query(WeChatUser).filter(WeChatUser.chat_name == chat_name).first()
        if not user:
            return False
        return sender.strip() in _parse_sender_blacklist(getattr(user, "sender_blacklist", None))
    except Exception as e:
        logger.warning("⚠️ 检查 sender 黑名单失败: chat='%s' sender='%s' error=%s", chat_name, sender, e)
        return False
    finally:
        db.close()


def _group_nickname_detection_state(chat_name: str) -> dict:
    """读取自动群昵称校准状态，不触碰微信 UI。"""
    chat_name = str(chat_name or "").strip()
    db = SessionLocal()
    try:
        user = db.query(WeChatUser).filter(WeChatUser.chat_name == chat_name).first()
        eligible = bool(
            user
            and user.is_group
            and bool(user.bot_group_nickname_auto_enabled)
        )
        return {
            "eligible": eligible,
            "nickname": (
                str(user.bot_group_nickname_detected or "").strip().lstrip("@").strip()
                if user
                else ""
            ),
        }
    except Exception as e:
        logger.warning("⚠️ 读取群昵称校准状态失败: chat='%s' error=%s", chat_name, e)
        return {"eligible": False, "nickname": "", "error": str(e)}
    finally:
        db.close()


def _store_group_nickname_from_ui(
    chat_name: str,
    detected_nickname: str,
    *,
    change_confirmed: bool = False,
    expected_previous: str | None = None,
) -> bool:
    """仅存储从微信“我在本群的昵称”控件精确读到的值。"""
    chat_name = str(chat_name or "").strip()
    nickname = str(detected_nickname or "").strip().lstrip("@").strip()
    if (
        not chat_name
        or not nickname
        or len(nickname) > 64
        or nickname.lower() in {"我", "自己", "self", "you"}
    ):
        return False

    db = SessionLocal()
    try:
        user = db.query(WeChatUser).filter(WeChatUser.chat_name == chat_name).first()
        if not user or not user.is_group or not bool(user.bot_group_nickname_auto_enabled):
            return False

        previous = str(user.bot_group_nickname_detected or "").strip()
        if expected_previous is not None:
            expected = str(expected_previous or "").strip().lstrip("@").strip()
            if previous != expected:
                logger.warning(
                    "⚠️ 群昵称确认期间数据库已变化，放弃旧候选值: "
                    "chat='%s' expected_previous='%s' actual_previous='%s' candidate='%s'",
                    chat_name,
                    expected,
                    previous,
                    nickname,
                )
                return False
        changed = previous != nickname
        if changed and not change_confirmed:
            logger.warning(
                "⚠️ 拒绝写入未二次确认的群昵称变化: chat='%s' '%s' -> '%s'",
                chat_name,
                previous or "(未设置)",
                nickname,
            )
            return False
        if changed and previous:
            try:
                aliases = json.loads(str(user.bot_group_nickname_aliases or "[]"))
            except (TypeError, ValueError, json.JSONDecodeError):
                aliases = []
            if not isinstance(aliases, list):
                aliases = []
            normalized_aliases = []
            for value in [previous, *aliases]:
                alias = str(value or "").strip().lstrip("@").strip()
                if alias and alias != nickname and alias not in normalized_aliases:
                    normalized_aliases.append(alias)
            user.bot_group_nickname_aliases = json.dumps(
                normalized_aliases[:8],
                ensure_ascii=False,
            )
        user.bot_group_nickname_detected = nickname
        user.bot_group_nickname_checked_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        db.commit()
        if changed:
            logger.info(
                "🤖 已从微信群详情更新机器人群昵称: chat='%s' '%s' -> '%s'",
                chat_name,
                previous or "(未设置)",
                nickname,
            )
        else:
            logger.debug("🤖 已从微信群详情确认机器人群昵称: %s -> %s", chat_name, nickname)
        return changed
    except Exception as e:
        db.rollback()
        logger.warning("⚠️ 保存微信群内机器人昵称失败: chat='%s' error=%s", chat_name, e)
        return False
    finally:
        db.close()


def _read_group_nickname_from_wechat_ui(chat_name: str) -> dict:
    """通过 mabowx 公共 API 读取本账号的群昵称。"""
    chat_name = str(chat_name or "").strip()
    client = wx
    if client is None:
        return {"status": "wechat_unavailable", "chat_name": chat_name}
    try:
        nickname = str(client.GetMyGroupNickname(chat_name) or "").strip()
        if not nickname:
            raise RuntimeError("mabowx returned an empty group nickname")
        return {
            "status": "success",
            "chat_name": chat_name,
            "nickname": nickname,
            "source": "mabowx.GetMyGroupNickname",
        }
    except Exception as e:
        return {
            "status": "nickname_value_not_found",
            "chat_name": chat_name,
            "message": str(e),
        }


def _read_confirmed_group_nickname_from_wechat_ui(chat_name: str) -> dict:
    """读取群昵称；若将发生变化，必须在同一目标群连续读到相同值。"""
    chat_name = str(chat_name or "").strip()
    state = _group_nickname_detection_state(chat_name)
    if not state.get("eligible"):
        return {
            "status": "auto_detection_disabled",
            "chat_name": chat_name,
            "message": str(state.get("error") or "该群未启用群昵称自动校准"),
        }

    first = _read_group_nickname_from_wechat_ui(chat_name)
    first_nickname = str(first.get("nickname") or "").strip().lstrip("@").strip()
    if first.get("status") != "success" or not first_nickname:
        return first

    previous = str(state.get("nickname") or "").strip().lstrip("@").strip()
    first["previous_nickname"] = previous
    if first_nickname == previous:
        first["confirmation"] = "unchanged"
        first["change_confirmed"] = False
        return first

    second = _read_group_nickname_from_wechat_ui(chat_name)
    second_nickname = str(second.get("nickname") or "").strip().lstrip("@").strip()
    if second.get("status") != "success" or second_nickname != first_nickname:
        return {
            "status": "nickname_confirmation_failed",
            "chat_name": chat_name,
            "message": "群昵称变化在二次精确读取中不一致，未写入数据库",
            "first_nickname": first_nickname,
            "second_nickname": second_nickname,
            "source": "mabowx.GetMyGroupNickname",
        }

    first["confirmation"] = "repeat_read"
    first["change_confirmed"] = True
    return first


def _group_nickname_probe_schedule(chat_name: str, now: float) -> tuple[bool, float]:
    """从数据库读取一次该群的下次校准时间，随后由内存缓存承担热路径。"""
    db = SessionLocal()
    try:
        user = db.query(WeChatUser).filter(WeChatUser.chat_name == chat_name).first()
        if not user or not user.is_group or not bool(user.bot_group_nickname_auto_enabled):
            return False, now + _BOT_NICKNAME_DISABLED_RECHECK_SEC

        checked_at = None
        if user.bot_group_nickname_checked_at:
            try:
                checked_at = datetime.strptime(
                    str(user.bot_group_nickname_checked_at),
                    "%Y-%m-%d %H:%M:%S",
                ).timestamp()
            except (TypeError, ValueError):
                checked_at = None
        return True, now if checked_at is None else checked_at + _BOT_NICKNAME_CONFIRM_INTERVAL_SEC
    except Exception as e:
        logger.debug("读取群昵称校准计划失败: chat='%s' error=%s", chat_name, e)
        return False, now + _BOT_NICKNAME_FAILURE_RETRY_SEC
    finally:
        db.close()


def _run_group_nickname_probe(chat_name: str) -> None:
    success = False
    result = {"status": "not_started", "chat_name": chat_name}
    try:
        result = _read_confirmed_group_nickname_from_wechat_ui(chat_name)
        nickname = str(result.get("nickname") or "").strip()
        if result.get("status") == "success" and nickname:
            _store_group_nickname_from_ui(
                chat_name,
                nickname,
                change_confirmed=bool(result.get("change_confirmed")),
                expected_previous=result.get("previous_nickname"),
            )
            success = True
        else:
            logger.warning("⚠️ 群昵称自动校准未读到明确值: %s", result)
    except Exception as e:
        logger.warning("⚠️ 群昵称自动校准失败: chat='%s' error=%s", chat_name, e)
    finally:
        now = time.time()
        with _bot_nickname_probe_lock:
            _bot_nickname_probe_running.discard(chat_name)
            _bot_nickname_probe_next_at[chat_name] = now + (
                _BOT_NICKNAME_CONFIRM_INTERVAL_SEC if success else _BOT_NICKNAME_FAILURE_RETRY_SEC
            )


def _maybe_schedule_group_nickname_probe(chat_name: str) -> bool:
    """在群消息热路径中做 O(1) 节流检查，到期时才后台读取一次 UI。"""
    chat_name = str(chat_name or "").strip()
    if not chat_name:
        return False

    now = time.time()
    with _bot_nickname_probe_lock:
        next_at = _bot_nickname_probe_next_at.get(chat_name)
        if next_at is None or now >= next_at:
            enabled, next_at = _group_nickname_probe_schedule(chat_name, now)
            _bot_nickname_probe_next_at[chat_name] = next_at
            if not enabled or now < next_at:
                return False
        else:
            return False
        if chat_name in _bot_nickname_probe_running:
            return False

        _bot_nickname_probe_running.add(chat_name)
        # 先占位，避免同时到达的消息重复创建任务。
        _bot_nickname_probe_next_at[chat_name] = now + _BOT_NICKNAME_CONFIRM_INTERVAL_SEC

    try:
        threading.Thread(
            target=_run_group_nickname_probe,
            args=(chat_name,),
            name=f"group-nickname-probe-{chat_name[:12]}",
            daemon=True,
        ).start()
        return True
    except Exception:
        with _bot_nickname_probe_lock:
            _bot_nickname_probe_running.discard(chat_name)
            _bot_nickname_probe_next_at[chat_name] = now + _BOT_NICKNAME_FAILURE_RETRY_SEC
        raise


def cache_message_for_later(chat_name: str, msg, prefix: str = "msg") -> str:
    """用 mabowx 的不可变投递 ID 缓存消息对象。"""

    delivery_id = str(getattr(msg, "delivery_id", "") or "").strip()
    if not delivery_id:
        raise RuntimeError("mabowx message is missing delivery_id")
    message_id = f"{prefix}_{delivery_id}"
    raw_message_id = str(getattr(msg, "id", "") or "")
    with message_cache_lock:
        chat_cache = message_cache.setdefault(chat_name, {})
        existing = chat_cache.get(message_id)
        if existing is not None and existing is not msg:
            raise RuntimeError(f"mabowx delivery_id collision: {delivery_id}")

        if message_id not in chat_cache and len(chat_cache) >= CACHE_MAX_SIZE:
            oldest_key = next(iter(chat_cache))
            del chat_cache[oldest_key]
        chat_cache[message_id] = msg

    logger.debug(
        "缓存消息投递: chat=%r message_id=%s raw_runtime_id=%s sequence=%s",
        chat_name,
        message_id,
        raw_message_id,
        int(getattr(msg, "delivery_sequence", 0) or 0),
    )
    return message_id


def _get_cached_message(chat_name: str, message_id: str):
    """Atomically resolve one immutable application message key."""

    with message_cache_lock:
        return message_cache.get(chat_name, {}).get(message_id)


def _find_tickle_target_message(messages, sender: str, *, is_group: bool):
    """Find the newest visible human message that can safely identify a peer."""

    expected_sender = str(sender or "").strip()
    if not expected_sender:
        return None
    for message in reversed(list(messages or [])):
        if str(getattr(message, "attr", "") or "") != "friend":
            continue
        if not callable(getattr(message, "tickle", None)):
            continue
        # A direct chat has only one peer; its chat title can be a remark while
        # the system notice uses the peer's nickname. Group chats must match
        # the resolved display name exactly to avoid tickling the wrong member.
        if is_group and str(getattr(message, "sender", "") or "").strip() != expected_sender:
            continue
        return message
    return None


def _message_identity(chat_name: str, msg) -> str:
    """返回 mabowx 为本次回调分配的投递 ID。"""
    delivery_id = str(getattr(msg, "delivery_id", "") or "").strip()
    if not delivery_id:
        raise RuntimeError("mabowx message is missing delivery_id")
    return f"{chat_name}:delivery:{delivery_id}"


















def _listener_status_meta_snapshot(desired_snapshot: dict) -> dict:
    now = time.time()
    result = {}
    for name, meta in desired_snapshot.items():
        enriched = dict(meta or {})
        for key in (
            "added_at",
            "last_attempt_at",
            "last_success_at",
            "last_reactivated_at",
            "last_failed_at",
            "last_rebind_at",
        ):
            value = float(enriched.get(key, 0.0) or 0.0)
            if value > 0:
                enriched[f"{key}_age_sec"] = round(now - value, 1)
        result[name] = enriched
    return result




















































def _listener_status_payload(desired_snapshot: dict, library_status: dict) -> dict:
    actual = list(library_status.get("actual") or [])
    actual_set = set(actual)
    missing = [name for name in desired_snapshot.keys() if name not in actual_set]
    if not desired_snapshot:
        listener_status = "empty"
    elif missing:
        listener_status = "degraded"
    else:
        listener_status = "healthy"

    return {
        "status": listener_status,
        "desired": list(desired_snapshot.keys()),
        "actual": actual,
        "missing": missing,
        "desired_meta": _listener_status_meta_snapshot(desired_snapshot),
        "probe_skipped": False,
        "actual_snapshot_at": time.time(),
        "registered": list(library_status.get("registered") or []),
        "windows": list(library_status.get("windows") or []),
        "window_auto_repair": dict(library_status.get("window_auto_repair") or {}),
        "listener_loop_running": bool(library_status.get("running")),
    }


def _mark_desired_listener_attempt(who: str) -> None:
    now = time.time()
    with desired_listeners_lock:
        meta = desired_listeners.setdefault(who, {
            "added_at": now,
            "last_reactivated_at": None,
            "reactivation_count": 0,
            "failure_count": 0,
        })
        meta.setdefault("added_at", now)
        meta.setdefault("reactivation_count", 0)
        meta.setdefault("failure_count", 0)
        meta["active"] = False
        meta["status"] = "activating"
        meta["last_attempt_at"] = now


def _mark_desired_listener_success(who: str, *, reactivated: bool = False) -> None:
    now = time.time()
    with desired_listeners_lock:
        meta = desired_listeners.setdefault(who, {
            "added_at": now,
            "last_reactivated_at": None,
            "reactivation_count": 0,
            "failure_count": 0,
        })
        meta.setdefault("added_at", now)
        meta["active"] = True
        meta["status"] = "active"
        meta["last_success_at"] = now
        meta["last_error"] = None
        meta["failure_count"] = 0
        if reactivated:
            meta["last_reactivated_at"] = now
            meta["reactivation_count"] = int(meta.get("reactivation_count", 0)) + 1


def _mark_desired_listener_failure(who: str, error: Exception | str) -> None:
    now = time.time()
    with desired_listeners_lock:
        meta = desired_listeners.setdefault(who, {
            "added_at": now,
            "last_reactivated_at": None,
            "reactivation_count": 0,
            "failure_count": 0,
        })
        meta["active"] = False
        meta["status"] = "error"
        meta["last_error"] = str(error)
        meta["last_failed_at"] = now
        meta["failure_count"] = int(meta.get("failure_count", 0)) + 1


def _add_listen_chat_verified(who: str, *, reactivated: bool = False) -> None:
    """Track application intent around mabowx's atomic listener API."""
    client = wx
    if client is None:
        raise RuntimeError("WeChat not connected")
    _mark_desired_listener_attempt(who)
    try:
        chat = client.AddListenChat(who, message_callback)
        if not chat:
            message = chat.get("message") if isinstance(chat, dict) else str(chat)
            raise RuntimeError(message or f"添加监听失败：{who}")
        _mark_desired_listener_success(who, reactivated=reactivated)
    except Exception as exc:
        _mark_desired_listener_failure(who, exc)
        raise


# --- 日志配置 ---
# 确保logs目录存在
os.makedirs("logs", exist_ok=True)

# 确保data目录存在
os.makedirs("data", exist_ok=True)

# 清除现有的日志配置，确保我们的配置生效
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

# 创建自定义的彩色日志格式
class ColoredFormatter(logging.Formatter):
    """自定义彩色日志格式化器"""
    
    # ANSI颜色代码
    COLORS = {
        'DEBUG': '\033[36m',    # 青色
        'INFO': '\033[32m',     # 绿色
        'WARNING': '\033[33m',  # 黄色
        'ERROR': '\033[31m',    # 红色
        'CRITICAL': '\033[35m', # 紫色
        'RESET': '\033[0m'      # 重置颜色
    }
    
    def format(self, record):
        # 获取原始格式化的消息
        formatted = super().format(record)
        
        # 为不同级别添加颜色
        level_name = record.levelname
        if level_name in self.COLORS:
            # 在级别名称前后添加颜色代码
            formatted = formatted.replace(
                f"[{level_name}]", 
                f"{self.COLORS[level_name]}[{level_name}]{self.COLORS['RESET']}"
            )
            # 为整个消息添加绿色（INFO级别）
            if level_name == 'INFO':
                formatted = f"{self.COLORS['INFO']}{formatted}{self.COLORS['RESET']}"
        
        return formatted

# 创建文件处理器（无颜色）
file_handler = create_rotating_file_handler("logs/wx_bot.log")
file_handler.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(name)s: %(message)s"))

# 创建控制台处理器（带颜色）
console_handler = logging.StreamHandler()
console_handler.setFormatter(ColoredFormatter("%(asctime)s [%(levelname)s] %(name)s: %(message)s"))

# 配置根日志记录器
logging.basicConfig(
    level=logging.INFO,
    handlers=[file_handler, console_handler],
    force=True  # 强制重新配置
)

# 配置第三方库日志级别，减少噪音
logging.getLogger("werkzeug").setLevel(logging.WARNING)  # Flask访问日志只记录警告以上
# mabowx 的控制台 handler 自行过滤 INFO；logger 保留 DEBUG 才能写入诊断文件。
logging.getLogger("mabowx").setLevel(logging.DEBUG)
logging.getLogger("requests").setLevel(logging.WARNING)  # requests库只记录警告
logging.getLogger("urllib3").setLevel(logging.WARNING)  # urllib3库只记录警告

logger = logging.getLogger(__name__)

# --- FastAPI主应用地址 ---
_web_port = os.getenv("WEB_PORT", "8888").strip() or "8888"
MAIN_APP_URL = os.getenv("MAIN_APP_URL", "").strip() or f"http://127.0.0.1:{_web_port}"


# --- 微信核心逻辑 ---
def _reset_listener_recovery_after_connection() -> None:
    """新连接不继承应用侧的监听注册状态。"""
    with desired_listeners_lock:
        for meta in desired_listeners.values():
            meta["active"] = False
            meta["status"] = "connection_ready_pending"
            meta["last_error"] = None
            meta["failure_count"] = 0


def _stop_wechat_client(client, reason: str) -> None:
    """释放 mabowx 后台资源，但保留微信客户端窗口。"""
    if client is None:
        return
    try:
        client.Dispose(timeout=3.0, wait=False)
        logger.info("已释放旧 mabowx 资源: reason=%s", reason)
    except Exception as e:
        logger.warning("释放旧 mabowx 资源失败: reason=%s error=%s", reason, e)


def start_wechat_logic():
    """初始化微信并保持运行，支持自动重连"""
    global wx, restart_requested, wechat_connection_generation

    retry_count = 0
    max_retries = 3
    base_delay = 10  # 基础重连延迟

    while True:
        current_client = None
        manual_restart = False
        retry_delay = base_delay
        disconnect_reason = "connection_cycle_end"
        try:
            # 在新线程中必须初始化COM
            comtypes.CoInitialize()

            logger.info(f"Initializing WeChat... (attempt {retry_count + 1})")
            # 只原子发布客户端引用；真实 UI 串行由 mabowx 负责。
            with wx_client_lock:
                current_client = WeChat(start_listener=True)
                wx = current_client
                wechat_connection_generation += 1
                _online_probe_mark_connected()
                _reset_listener_recovery_after_connection()
            logger.info(
                "✅ WeChat connected successfully! connection_id=%s:%s",
                wechat_service_instance_id,
                wechat_connection_generation,
            )
            # 重置重试计数
            retry_count = 0

            # 启动KeepRunning在单独线程中，然后进入监控循环
            logger.info("Starting KeepRunning in background...")
            # 必须捕获本轮对象；不能让旧线程在重连后读取新的全局 wx。
            keep_running_thread = threading.Thread(
                target=current_client.KeepRunning,
                name="mabowx_keep_running",
                daemon=True,
            )
            keep_running_thread.start()

            # 进入监控循环，定期检查重启请求和微信状态
            logger.info("Starting monitoring loop...")
            while True:
                # 检查重启请求
                if restart_requested:
                    logger.info("🔄 检测到重启请求，退出当前连接...")
                    restart_requested = False
                    manual_restart = True
                    disconnect_reason = "manual_restart"
                    break

                probe_started = time.perf_counter()
                if wx is not current_client:
                    disconnect_reason = "connection_replaced"
                    break
                try:
                    online = bool(current_client.IsOnline())
                    duration_ms = (time.perf_counter() - probe_started) * 1000
                    probe = _online_probe_record_result(online, duration_ms)
                except Exception as check_e:
                    duration_ms = (time.perf_counter() - probe_started) * 1000
                    probe = _online_probe_record_error(check_e, duration_ms)

                if not probe.get("online"):
                    logger.warning(
                        "⚠️ 微信在线状态已确认异常，将重新连接: state=%s "
                        "failures=%s/%s kind=%s error=%s duration_ms=%s",
                        probe.get("state"),
                        probe.get("consecutive_failures"),
                        probe.get("failure_threshold"),
                        probe.get("last_failure_kind"),
                        probe.get("last_error"),
                        probe.get("last_duration_ms"),
                    )
                    disconnect_reason = "wechat_offline_confirmed"
                    break

                if probe.get("state") == "suspect":
                    logger.debug(
                        "微信在线探针瞬时失败，保留已确认连接: failures=%s/%s "
                        "kind=%s error=%s duration_ms=%s",
                        probe.get("consecutive_failures"),
                        probe.get("failure_threshold"),
                        probe.get("last_failure_kind"),
                        probe.get("last_error"),
                        probe.get("last_duration_ms"),
                    )

                # 等待5秒后再次检查
                time.sleep(ONLINE_PROBE_INTERVAL_SEC)

            # 退出监控循环，准备重连
            logger.info("🔄 准备重新连接...")

        except Exception as e:
            logger.error(f"❌ WeChat connection failed: {e}", exc_info=True)
            disconnect_reason = f"connection_failed:{e}"
            retry_count += 1

            if retry_count > max_retries:
                logger.error(f"❌ WeChat connection failed after {max_retries} attempts, entering continuous retry mode")
                # 进入持续重试模式，但延长间隔
                retry_delay = min(300, base_delay * (2 ** min(retry_count - max_retries, 5)))  # 最多5分钟
            else:
                retry_delay = base_delay * retry_count

            logger.info(f"🔄 Will retry WeChat connection in {retry_delay} seconds...")

        finally:
            with wx_client_lock:
                if wx is current_client:
                    wx = None
                _stop_wechat_client(current_client, disconnect_reason)
            _online_probe_mark_disconnected(disconnect_reason)

            # 确保COM被正确卸载
            try:
                comtypes.CoUninitialize()
            except Exception:
                pass

        # 确定重连延迟时间
        if manual_restart:
            logger.info("🔄 手动重启，立即尝试重连...")
            delay = 2  # 手动重启短暂等待
        else:
            # 自动重连：使用计算的延迟或默认值
            delay = retry_delay
            logger.info(f"🔄 等待 {delay} 秒后重连...")

        time.sleep(delay)

        logger.info("🔄 Attempting to reconnect WeChat...")


def check_summary_permission(chat_name: str) -> bool:
    """
    检查聊天是否启用了摘要功能
    
    Args:
        chat_name: 聊天名称
        
    Returns:
        是否启用摘要功能
    """
    try:
        # 从数据库查询用户权限
        db = SessionLocal()
        try:
            user = db.query(WeChatUser).filter(WeChatUser.chat_name == chat_name).first()
            if user:
                # 检查用户是否有摘要插件权限
                allowed_plugins = {p.plugin_name for p in user.permissions}
                summary_plugins = {"builtin_summary", "summary_plus"}
                # 支持多级目录插件名匹配（完整键）
                if allowed_plugins.intersection(summary_plugins):
                    return True
                # 检查末级简名匹配
                base_plugins = {p.rsplit('/', 1)[-1] for p in allowed_plugins}
                if base_plugins.intersection(summary_plugins):
                    return True
                return False
            else:
                # 如果用户不在权限表中，默认允许（保持向后兼容）
                logger.debug(f"用户 '{chat_name}' 不在权限表中，默认允许摘要功能")
                return True
        finally:
            db.close()
    except Exception as e:
        logger.warning(f"⚠️ 检查摘要权限失败: {e}")
        # 如果检查失败，默认允许（保持向后兼容）
        return True









































def _log_image_download_audit(
    kind: str,
    chat_name: str,
    message_id: str,
    file_path: str,
    msg=None,
) -> dict:
    audit = image_file_fingerprint(file_path)
    get_media_audit = getattr(msg, "get_media_audit", None)
    verification = dict(get_media_audit() if callable(get_media_audit) else {})
    variant_metrics = json.dumps(
        verification.get("variant_metrics") or [],
        ensure_ascii=False,
        separators=(",", ":"),
    )
    matched = verification.get("matched")
    result = (
        "accepted"
        if matched is True
        else "rejected"
        if matched is False
        else "recorded"
    )
    file_name = os.path.basename(str(audit.get("path") or ""))
    logger.info(
        "🧷 图片绑定: result=%s rule=%s profile=%s kind=%s chat=%r "
        "message_id=%s route=%s phash=%s color=%s detail=%s variant=%s "
        "target=%sx%s file=%sx%s name=%r",
        result,
        verification.get("match_rule") or "unknown",
        verification.get("match_profile") or "unknown",
        kind,
        chat_name,
        message_id,
        verification.get("route"),
        verification.get("phash_distance"),
        verification.get("color_distance"),
        verification.get("detail_distance"),
        verification.get("variant"),
        verification.get("target_width"),
        verification.get("target_height"),
        audit.get("width"),
        audit.get("height"),
        file_name,
    )
    logger.debug(
        "🧷 图片绑定详情: chat=%r message_id=%s delivery_id=%s raw_runtime_id=%s "
        "target_aspect=%s target_variance=%s target_rect=%s "
        "thresholds=%s variants=%s "
        "path=%r bytes=%s sha256=%s format=%s",
        chat_name,
        message_id,
        verification.get("delivery_id") or getattr(msg, "delivery_id", ""),
        verification.get("raw_message_id") or getattr(msg, "id", ""),
        verification.get("target_aspect_ratio"),
        verification.get("target_variance"),
        verification.get("target_rect"),
        json.dumps(
            verification.get("match_thresholds") or {},
            ensure_ascii=False,
            separators=(",", ":"),
        ),
        variant_metrics,
        audit.get("path"),
        audit.get("bytes"),
        audit.get("sha256"),
        audit.get("format"),
    )
    return audit









































def _download_inbound_file(msg, *, chat_name: str, sender: str, received_at: float) -> dict:
    """Download one live FileMessage into managed per-message storage."""
    store = get_wechat_file_store()
    file_id = f"file_{uuid.uuid4().hex}"
    source_message_id = _message_identity(chat_name, msg)
    original_filename = extract_file_name_from_message(getattr(msg, "content", ""))
    download_dir = store.prepare_download_dir(
        chat_name=chat_name,
        file_id=file_id,
        received_at=received_at,
    )
    store.record(
        file_id=file_id,
        source_message_id=source_message_id,
        chat_name=chat_name,
        sender=sender,
        original_filename=original_filename or f"{file_id}.bin",
        received_at=received_at,
        status="downloading",
    )

    try:
        timeout = _bounded_env_int("WECHAT_FILE_DOWNLOAD_TIMEOUT_SEC", 60, 5)
        result = msg.download(dir_path=download_dir, timeout=timeout)

        if not isinstance(result, (str, os.PathLike)):
            message = getattr(result, "message", None) or str(result)
            raise RuntimeError(f"mabowx file download failed: {message}")

        downloaded_path = os.path.abspath(os.fspath(result))
        managed_root = os.path.abspath(os.fspath(download_dir))
        try:
            is_managed = os.path.commonpath([downloaded_path, managed_root]) == managed_root
        except ValueError:
            is_managed = False
        if not is_managed:
            raise RuntimeError("mabowx returned a file outside the managed download directory")
        if not os.path.isfile(downloaded_path):
            raise FileNotFoundError(f"downloaded file does not exist: {downloaded_path}")

        file_name = os.path.basename(downloaded_path) or original_filename or f"{file_id}.bin"
        display_name = original_filename or file_name
        file_size = os.path.getsize(downloaded_path)
        digest = sha256_file(Path(downloaded_path))
        record = store.record(
            file_id=file_id,
            source_message_id=source_message_id,
            chat_name=chat_name,
            sender=sender,
            original_filename=display_name,
            received_at=received_at,
            status="ready",
            saved_path=downloaded_path,
            file_size=file_size,
            sha256=digest,
        )
        logger.info(
            "📁 微信文件已归档: chat=%s sender=%s file_id=%s name=%s bytes=%s",
            chat_name,
            sender,
            file_id,
            display_name,
            file_size,
        )
        return record
    except Exception as exc:
        record = store.record(
            file_id=file_id,
            source_message_id=source_message_id,
            chat_name=chat_name,
            sender=sender,
            original_filename=original_filename or f"{file_id}.bin",
            received_at=received_at,
            status="failed",
            download_error=str(exc),
        )
        logger.error(
            "❌ 微信文件自动下载失败: chat=%s sender=%s file_id=%s name=%s error=%s",
            chat_name,
            sender,
            file_id,
            original_filename,
            exc,
        )
        return record


def _resolve_quoted_file(*, chat_name: str, quote_content: str, received_at: float) -> dict:
    """Resolve only an exact filename match from the current chat."""
    if not looks_like_file_quote(quote_content):
        return {}
    try:
        resolution = get_wechat_file_store().resolve_quote(
            chat_name=chat_name,
            quote_content=quote_content,
            before_timestamp=received_at,
        )
    except Exception as exc:
        logger.error("❌ 引用文件索引查询失败: chat=%s quote=%r error=%s", chat_name, quote_content, exc)
        return {
            "has_quote_file": True,
            "quoted_file_name": str(quote_content or "").strip(),
            "quoted_file_status": "index_error",
            "quoted_file_error": str(exc),
        }

    record = resolution.record or {}
    payload = {
        "has_quote_file": resolution.status != "not_file",
        "quoted_file_id": record.get("file_id"),
        "quoted_file_name": resolution.file_name,
        "quoted_file_path": record.get("saved_path") if resolution.status == "ready" else None,
        "quoted_file_size": record.get("file_size"),
        "quoted_file_sha256": record.get("sha256"),
        "quoted_file_status": resolution.status,
        "quoted_file_candidate_count": resolution.candidate_count,
        "quoted_file_error": record.get("download_error"),
    }
    if resolution.status == "ready":
        logger.info(
            "📎 引用文件已精确绑定: chat=%s file_id=%s name=%s candidates=%s",
            chat_name,
            record.get("file_id"),
            resolution.file_name,
            resolution.candidate_count,
        )
    else:
        logger.warning(
            "⚠️ 引用内容像文件名但未找到可用归档: chat=%s name=%s status=%s",
            chat_name,
            resolution.file_name,
            resolution.status,
        )
    return payload

def message_callback(msg, chat):
    """
    处理收到的消息回调函数
    参数:
        msg: 消息对象
        chat: 聊天对象
    """
    try:
        message_attr = getattr(msg, 'attr', None)
        is_tickle = bool(getattr(msg, "is_tickle", False))
        # 自己发送的消息不转发给插件（避免回环）。
        if message_attr == 'self':
            return

        # 普通系统消息不进入业务层；结构化的“拍一拍”是唯一例外。
        if message_attr != 'friend' and not is_tickle:
            return
            
        # 获取聊天名称
        chat_info = chat.ChatInfo() or {}
        chat_name = chat_info.get("chat_name", "Unknown")
        is_group_chat = str(chat_info.get("chat_type") or "").lower() == "group"
        tickle_from = str(getattr(msg, "tickle_from", "") or "").strip()
        tickle_to = str(getattr(msg, "tickle_to", "") or "").strip()
        tickle_suffix = str(getattr(msg, "tickle_suffix", "") or "").strip()
        sender_name = (
            tickle_from
            if is_tickle
            else str(getattr(msg, "sender", "") or "").strip()
        )

        if _is_sender_blacklisted_for_chat(chat_name, sender_name):
            logger.info("🚫 Sender 命中群/用户级黑名单，跳过所有插件处理: chat='%s' sender='%s'", chat_name, sender_name)
            return

        # mabowx 在消息源头按可见列表尾锚点去重，并为每次投递
        # 分配 delivery_id。应用层不再以“发送者+文本”重复判断。
        # 优化日志记录
        quote_nickname = str(getattr(msg, 'quote_nickname', '') or '').strip()
        quote_content_raw = getattr(msg, 'quote_content', '') or ''
        quote_content_str = str(quote_content_raw)
        # 单行化：转义换行/回车，便于日志检索
        quote_content_one_line = quote_content_str.replace('\r', '\\r').replace('\n', '\\n')
        # 截断：最多 20 字（超出追加...）
        if len(quote_content_one_line) > 20:
            quote_content_one_line = quote_content_one_line[:20] + "..."
        quote_content_part = f", quote_content='{quote_content_one_line}'" if quote_content_one_line else ""
        logger.info(
            f"📥 Received message: "
            f"sender='{msg.sender}', "
            f"chat='{chat_name}', "
            f"type='{msg.type}', "
            f"content='{str(msg.content)}'"
            f"{quote_content_part}"
            
        )
        
        received_at = time.time()

        # 初始化额外数据
        url = None
        url_hint = {}
        quote_image_path = None
        inbound_file = {}
        quoted_file = {}

        if msg.type == "file":
            inbound_file = _download_inbound_file(
                msg,
                chat_name=chat_name,
                sender=sender_name,
                received_at=received_at,
            )
        
        get_url_hint = getattr(msg, "get_url_hint", None)
        if callable(get_url_hint):
            try:
                url_hint = dict(get_url_hint() or {})
            except Exception as exc:
                logger.warning("mabowx URL 提示解析失败: %s", exc)
        if url_hint.get("kind") == "inline":
            url = str(url_hint.get("url") or "") or None
            if url:
                logger.info("✅ 从 mabowx 消息元数据取得 URL: %s", url)

        # 折叠文本只在业务上允许摘要时调用库的完整文本解析。
        if not url and url_hint.get("kind") == "folded":
            if check_summary_permission(chat_name):
                logger.info("🔗 检测到“...更多”折叠文本，尝试右键复制完整文本解析URL")
                get_url = getattr(msg, "get_url", None)
                if callable(get_url):
                    try:
                        url = get_url(timeout=3.0)
                    except Exception as exc:
                        logger.warning("折叠消息 URL 解析失败: %s", exc)
            else:
                logger.info(f"🔗 检测到“...更多”折叠文本，但聊天 '{chat_name}' 未启用摘要功能，跳过右键复制解析")

        # 链接卡片暂存消息对象，需要时再由 mabowx 打开并解析。
        link_message_id = None
        if not url and url_hint.get("kind") == "card":
            link_message_id = cache_message_for_later(chat_name, msg, prefix="link")
            logger.info("🔗 检测到 [链接] 卡片消息，已缓存以便按需解析URL: %s:%s", chat_name, link_message_id)
            if not check_summary_permission(chat_name):
                logger.info(f"🔗 检测到 [链接] 卡片消息，但聊天 '{chat_name}' 未启用摘要功能，跳过点击操作")

        # 处理图片消息 - 缓存消息对象以供后续下载
        has_quote_image = False
        quote_image_path = None
        has_quote_video = False
        quote_video_path = None
        message_id = None
        normalized_quote_content = getattr(msg, 'quote_content', '')

        if msg.type == "quote":
            logger.info("📎 检测到引用消息")
            # 检查引用内容是否包含图片
            quote_content = getattr(msg, 'quote_content', '')
            # 兼容不同客户端/库版本：引用图片可能表现为 "[图片]" 或仅为 "图片"
            quote_content_stripped = str(quote_content).strip()
            if ('[图片]' in quote_content) or (quote_content_stripped == '图片'):
                logger.info("🖼️ 检测到引用图片，暂不下载（等待插件按需请求）")
                has_quote_image = True
                # 归一化：主程序与插件侧均以 "[图片]" 作为引用图片标记
                if quote_content_stripped == '图片' and '[图片]' not in str(quote_content):
                    logger.info("🧩 引用图片标记归一化: '图片' -> '[图片]'")
                normalized_quote_content = "[图片]"
            elif ('[视频]' in quote_content) or (quote_content_stripped == '视频'):
                logger.info("🎬 检测到引用视频，暂不下载（等待助手按需请求）")
                has_quote_video = True
                normalized_quote_content = "[视频]"
            else:
                normalized_quote_content = quote_content
                quoted_file = _resolve_quoted_file(
                    chat_name=chat_name,
                    quote_content=quote_content,
                    received_at=received_at,
                )

        # 为所有图片消息缓存消息对象
        if msg.type == "image":
            logger.info("🖼️ 检测到直接图片消息，缓存消息对象")
            # 缓存消息对象以供后续按需下载
            message_id = cache_message_for_later(chat_name, msg, prefix="image")
            logger.info(
                "🔄 缓存直接图片消息: chat=%r message_id=%s raw_runtime_id=%s sequence=%s",
                chat_name,
                message_id,
                str(getattr(msg, "id", "") or ""),
                int(getattr(msg, "delivery_sequence", 0) or 0),
            )
        elif msg.type == "quote" and has_quote_image:
            logger.info("🖼️ 检测到引用图片，暂不下载（等待插件按需请求）")
            # 缓存消息对象以供后续按需下载
            message_id = cache_message_for_later(chat_name, msg, prefix="quote_image")
            logger.debug(f"🔄 缓存引用图片消息: {chat_name}:{message_id}")
        elif msg.type == "quote" and has_quote_video:
            message_id = cache_message_for_later(chat_name, msg, prefix="quote_video")
            logger.info("🎬 缓存引用视频消息: %s:%s", chat_name, message_id)
        
        # 序列化消息内容
        # 如果成功解析出URL，则将mtype标记为link，便于主应用识别为链接事件
        resolved_mtype = getattr(msg, 'mtype', msg.type)
        if url:
            resolved_mtype = 'link'

        # 为图片消息生成message_id
        final_message_id = None
        if msg.type == "image":
            final_message_id = message_id
        elif has_quote_image:
            final_message_id = message_id
        elif has_quote_video:
            final_message_id = message_id
        elif msg.type == "file" and inbound_file:
            final_message_id = inbound_file.get("file_id")
        elif link_message_id:
            final_message_id = link_message_id
        elif resolved_mtype == "link" or bool(url_hint):
            # 常规 URL 文本也需要保留原始 mabowx 消息对象，摘要生成完成后
            # 才能通过 message_id 调用 msg.quote(...) 引用回复。
            final_message_id = cache_message_for_later(chat_name, msg, prefix="link")
            logger.debug(f"🔄 缓存链接消息用于后续引用回复: {chat_name}:{final_message_id}")

        msg_data = {
            "content": msg.content,
            "sender": sender_name,
            "sender_id": str(
                getattr(msg, "sender_id", None)
                or getattr(msg, "wxid", None)
                or ""
            ).strip() or None,
            "sender_remark": str(
                getattr(msg, "sender_remark", None) or ""
            ).strip() or None,
            "chat_name": chat_name,
            "is_group": is_group_chat,
            "type": msg.type,
            "mtype": resolved_mtype,  # 使用解析后的mtype
            "message_id": final_message_id,  # 消息ID，用于后续操作
            "url": url,  # 添加URL字段
            "quote_image_path": quote_image_path,  # 引用图片路径（延迟下载时为None）
            "quote_nickname": quote_nickname or None,  # 被引用消息发送者的群内显示名
            "quote_content": normalized_quote_content,  # 添加引用内容字段（已做引用图片标记归一化）
            "has_quote_image": has_quote_image,  # 标记是否有引用图片需要按需下载
            "quote_video_path": quote_video_path,
            "has_quote_video": has_quote_video,
            "file_id": inbound_file.get("file_id"),
            "file_name": inbound_file.get("original_filename"),
            "file_path": inbound_file.get("saved_path"),
            "file_size": inbound_file.get("file_size"),
            "file_sha256": inbound_file.get("sha256"),
            "file_status": inbound_file.get("status"),
            "file_error": inbound_file.get("download_error"),
            "has_quote_file": bool(quoted_file.get("has_quote_file")),
            "quoted_file_id": quoted_file.get("quoted_file_id"),
            "quoted_file_name": quoted_file.get("quoted_file_name"),
            "quoted_file_path": quoted_file.get("quoted_file_path"),
            "quoted_file_size": quoted_file.get("quoted_file_size"),
            "quoted_file_sha256": quoted_file.get("quoted_file_sha256"),
            "quoted_file_status": quoted_file.get("quoted_file_status"),
            "quoted_file_candidate_count": quoted_file.get("quoted_file_candidate_count", 0),
            "quoted_file_error": quoted_file.get("quoted_file_error"),
            "is_tickle": is_tickle,
            "tickle_from": tickle_from or None,
            "tickle_to": tickle_to or None,
            "tickle_suffix": tickle_suffix or None,
            "timestamp": received_at,
        }
        
        # 发送到主应用
        try:
            response = requests.post(
                f"{MAIN_APP_URL}/api/internal/wechat_message",
                json=msg_data,
                timeout=30 # 30秒超时，足够图片下载
            )
            response.raise_for_status() # 如果请求失败则抛出异常
            logger.debug(f"Message forwarded to main app, status: {response.status_code}")
        except requests.RequestException as e:
            logger.error(f"Failed to forward message to main app: {e}")

        # 校准在后台线程中执行；每群每 24 小时最多一次，不阻塞消息转发。
        if is_group_chat:
            _maybe_schedule_group_nickname_probe(chat_name)

    except Exception as e:
        logger.error(f"Error processing message: {e}")


# --- Flask API 端点 ---
@app.route('/api/send_message', methods=['POST'])
def send_message():
    """发送消息"""
    if not wx:
        return jsonify({"status": "error", "message": "WeChat not connected"}), 503
    
    data = request.json or {}
    who = data.get('who')
    msg = data.get('message')
    raw_at_users = data.get('at_users')
    if isinstance(raw_at_users, str):
        raw_at_users = [raw_at_users]
    at_users = [
        str(user).strip().lstrip('@').strip()
        for user in (raw_at_users or [])
        if str(user).strip().lstrip('@').strip()
    ]
    request_id = str(data.get('request_id') or "").strip()[:128]
    if not request_id:
        request_id = uuid.uuid4().hex
    
    if not who or not msg:
        return jsonify({"status": "error", "message": "Missing 'who' or 'message'"}), 400
        
    request_started_at = time.monotonic()
    logger.info(
        "Text send request received: request_id=%s chat=%s preview=%s...",
        request_id,
        who,
        msg[:50],
    )

    def _send_once() -> dict:
        client = wx
        if client is None:
            raise RuntimeError("WeChat not connected")
        started_at = time.monotonic()
        response = client.SendMsg(
            msg=msg,
            who=who,
            at=at_users or None,
            exact=True,
            max_retries=1,
        )
        payload = (
            response.to_dict()
            if callable(getattr(response, "to_dict", None))
            else dict(response) if isinstance(response, dict) else {}
        )
        details = dict(payload.get("data") or {})
        return {
            "success": bool(response),
            "route": details.get("route"),
            "attempts": list(details.get("attempts") or []),
            "elapsed_ms": round((time.monotonic() - started_at) * 1000, 1),
            # 保留字段兼容现有 HTTP 客户端；UI 锁已由 mabowx 内部管理。
            "lock_wait_ms": 0.0,
            "library_response": payload,
        }

    try:
        result = outbound_text_deduplicator.run(
            ("text", request_id),
            _send_once,
        )
    except TimeoutError as e:
        logger.warning(
            "Duplicate text request is still in progress: request_id=%s chat=%s error=%s",
            request_id,
            who,
            e,
        )
        response = jsonify({
            "status": "busy",
            "message": "Original send request is still in progress",
            "request_id": request_id,
        })
        response.status_code = 503
        response.headers["Retry-After"] = "5"
        return response
    except Exception as e:
        logger.error(
            "Text send orchestration failed: request_id=%s chat=%s error=%s",
            request_id,
            who,
            e,
            exc_info=True,
        )
        return jsonify({
            "status": "error",
            "message": str(e),
            "request_id": request_id,
        }), 500

    attempts = result.get("attempts") or []
    last_attempt = attempts[-1] if attempts else {}
    total_ms = round((time.monotonic() - request_started_at) * 1000, 1)
    response_body = {
        "status": "success" if result.get("success") else "error",
        "message": "Message sent" if result.get("success") else "Failed to send message",
        "request_id": request_id,
        "route": result.get("route") or last_attempt.get("route"),
        "attempt_count": len(attempts),
        "lock_wait_ms": result.get("lock_wait_ms"),
        "send_elapsed_ms": result.get("elapsed_ms"),
        "total_elapsed_ms": total_ms,
        "attempts": attempts,
    }

    if result.get("success"):
        logger.info(
            "Text send completed: request_id=%s chat=%s route=%s attempts=%s "
            "lock_wait_ms=%s send_ms=%s total_ms=%s",
            request_id,
            who,
            response_body["route"],
            response_body["attempt_count"],
            response_body["lock_wait_ms"],
            response_body["send_elapsed_ms"],
            total_ms,
        )
        return jsonify(response_body)

    logger.error(
        "Text send failed: request_id=%s chat=%s attempts=%s lock_wait_ms=%s "
        "send_ms=%s total_ms=%s last_response=%s last_error=%s",
        request_id,
        who,
        response_body["attempt_count"],
        response_body["lock_wait_ms"],
        response_body["send_elapsed_ms"],
        total_ms,
        last_attempt.get("response"),
        last_attempt.get("error"),
    )
    return jsonify(response_body), 500


@app.route('/api/bot_nickname/probe', methods=['POST'])
def probe_bot_group_nickname():
    """立即从微信群详情读取并保存本账号的群昵称。"""
    if not wx:
        return jsonify({"status": "error", "message": "WeChat not connected"}), 503
    data = request.json or {}
    who = str(data.get("who") or "").strip()
    if not who:
        return jsonify({"status": "error", "message": "Missing 'who'"}), 400
    try:
        result = _read_confirmed_group_nickname_from_wechat_ui(who)
        nickname = str(result.get("nickname") or "").strip()
        if result.get("status") == "success" and nickname:
            result["changed"] = _store_group_nickname_from_ui(
                who,
                nickname,
                change_confirmed=bool(result.get("change_confirmed")),
                expected_previous=result.get("previous_nickname"),
            )
            with _bot_nickname_probe_lock:
                _bot_nickname_probe_next_at[who] = time.time() + _BOT_NICKNAME_CONFIRM_INTERVAL_SEC
        return jsonify(result), (200 if result.get("status") == "success" else 422)
    except Exception as e:
        logger.error("读取群内机器人昵称 UI 失败: %s", e)
        return jsonify({"status": "error", "message": str(e)}), 500


@app.route('/api/quote_message', methods=['POST'])
def quote_message():
    """引用缓存中的原消息并回复文本。"""
    if not wx:
        return jsonify({"status": "error", "message": "WeChat not connected"}), 503

    data = request.json or {}
    chat_name = data.get('chat_name')
    message_id = data.get('message_id')
    reply_text = data.get('message')

    if not chat_name or not message_id or not reply_text:
        return jsonify({
            "status": "error",
            "message": "Missing 'chat_name', 'message_id' or 'message'"
        }), 400

    try:
        original_message = _get_cached_message(chat_name, message_id)
        if original_message is None:
            return jsonify({
                "status": "error",
                "message": f"Message not found in cache: {chat_name}:{message_id}"
            }), 404

        quote = getattr(original_message, 'quote', None)
        if not callable(quote):
            return jsonify({
                "status": "error",
                "message": "Current mabowx message object does not support quote()"
            }), 501

        logger.info("Replying with quote to %s:%s: %s...", chat_name, message_id, reply_text[:50])
        result = quote(reply_text)

        if result:
            return jsonify({"status": "success", "message": "Quoted message sent"})

        result_message = result.get('message') if isinstance(result, dict) else str(result)
        return jsonify({
            "status": "error",
            "message": result_message or "Failed to quote message"
        }), 500
    except Exception as e:
        logger.error("Error replying with quote: %s", e, exc_info=True)
        return jsonify({"status": "error", "message": str(e)}), 500


@app.route('/api/tickle_message', methods=['POST'])
def tickle_message():
    """拍一拍指定聊天中发起拍一拍的成员。"""
    client = wx
    if client is None:
        return jsonify({"status": "error", "message": "WeChat not connected"}), 503

    data = request.json or {}
    chat_name = str(data.get("chat_name") or "").strip()
    sender = str(data.get("sender") or "").strip()
    if not chat_name or not sender:
        return jsonify({
            "status": "error",
            "message": "Missing 'chat_name' or 'sender'",
        }), 400

    try:
        chat = client.GetListenChat(chat_name, include_open_window=True)
        if chat is None:
            return jsonify({
                "status": "error",
                "message": f"Listening chat is unavailable: {chat_name}",
            }), 404

        bound_name = str(getattr(chat, "who", "") or "").strip()
        chat_info = chat.ChatInfo() or {}
        actual_name = str(chat_info.get("chat_name") or "").strip()
        if bound_name != chat_name or actual_name != chat_name:
            return jsonify({
                "status": "error",
                "message": (
                    "Listening chat identity mismatch: "
                    f"expected={chat_name!r}, bound={bound_name!r}, actual={actual_name!r}"
                ),
            }), 409

        is_group = str(chat_info.get("chat_type") or "").lower() == "group"
        target_message = _find_tickle_target_message(
            chat.GetAllMessage(),
            sender,
            is_group=is_group,
        )
        if target_message is None:
            return jsonify({
                "status": "error",
                "message": f"No visible message found for tickle sender: {sender}",
            }), 404

        result = target_message.tickle()
        if result:
            logger.info("👋 已回拍 chat=%s sender=%s", chat_name, sender)
            return jsonify({
                "status": "success",
                "message": "Tickle sent",
                "sender": sender,
            })

        result_message = result.get("message") if isinstance(result, dict) else str(result)
        return jsonify({
            "status": "error",
            "message": result_message or "Failed to tickle message sender",
        }), 500
    except Exception as e:
        logger.error(
            "Error tickling message sender: chat=%s sender=%s error=%s",
            chat_name,
            sender,
            e,
            exc_info=True,
        )
        return jsonify({"status": "error", "message": str(e)}), 500

@app.route('/api/add_listener', methods=['POST'])
def add_listener():
    """添加聊天监听"""
    if not wx:
        return jsonify({"status": "error", "message": "WeChat not connected"}), 503

    data = request.json
    who = data.get('who')

    if not who:
        return jsonify({"status": "error", "message": "Missing 'who'"}), 400

    try:
        logger.info(f"Adding listener for {who}...")
        _add_listen_chat_verified(who)
        return jsonify({"status": "success", "message": f"Listener added for {who}"})
    except Exception as e:
        logger.error(
            "Error adding listener: chat=%s error=%s",
            who,
            e,
            exc_info=True,
        )
        return jsonify({"status": "error", "message": str(e)}), 500
@app.route('/api/remove_listener', methods=['POST'])
def remove_listener():
    """移除聊天监听"""
    data = request.json
    who = data.get('who')

    if not who:
        return jsonify({"status": "error", "message": "Missing 'who'"}), 400

    with desired_listeners_lock:
        desired_listeners.pop(who, None)

    if not wx:
        return jsonify({
            "status": "success",
            "message": f"Listener removed from desired list for {who}; WeChat not connected"
        })

    try:
        logger.info(f"Removing listener for {who}...")
        client = wx
        if client is not None:
            client.RemoveListenChat(who)
        return jsonify({"status": "success", "message": f"Listener removed for {who}"})
    except Exception as e:
        logger.error(f"Error removing listener: {e}")
        return jsonify({"status": "error", "message": str(e)}), 500

@app.route('/api/get_friends', methods=['GET'])
def get_friends():
    """获取所有好友列表"""
    if not wx:
        return jsonify({"status": "error", "message": "WeChat not connected"}), 503

    try:
        # 获取查询参数
        keywords = request.args.get('keywords')
        
        friends = wx.GetAllFriends(keywords=keywords)
        # friends 对象可能包含不能直接json序列化的内容，需要挑选字段
        friends_list = [
            {
                'wxid': friend.get('wxid'),
                'nickname': friend.get('nickname'),
                'remark': friend.get('remark')
            } for friend in friends
        ]
        return jsonify({"status": "success", "friends": friends_list})
    except Exception as e:
        logger.error(f"Error getting friends list: {e}")
        return jsonify({"status": "error", "message": str(e)}), 500

@app.route('/api/get_groups', methods=['GET'])
def get_groups():
    """获取所有最近群聊列表"""
    if not wx:
        return jsonify({"status": "error", "message": "WeChat not connected"}), 503

    try:
        groups = wx.GetAllRecentGroups()
        # groups 对象是元组列表 `(name, count)`
        groups_list = [
            {
                'name': group[0],
                'member_count': group[1]
            } for group in groups
        ]
        return jsonify({"status": "success", "groups": groups_list})
    except Exception as e:
        logger.error(f"Error getting groups list: {e}")
        return jsonify({"status": "error", "message": str(e)}), 500

@app.route('/api/get_my_info', methods=['GET'])
def get_my_info():
    """获取当前登录账号信息"""
    if not wx:
        return jsonify({"status": "error", "message": "WeChat not connected"}), 503

    try:
        if not hasattr(wx, 'GetMyInfo'):
             return jsonify({"status": "error", "message": "wx.GetMyInfo not supported in this version"}), 501
             
        info = wx.GetMyInfo()
        #logger.info(f"🔍 DEBUG: wx.GetMyInfo() returned: {info}")
        
        # info 字典通常包含 'name', 'id', 'bm' (avatar path?) 等
        # 确保只返回可序列化数据
        return jsonify({"status": "success", "info": info})
    except Exception as e:
        logger.error(f"Error getting my info: {e}")
        return jsonify({"status": "error", "message": str(e)}), 500

@app.route('/api/send_url_card', methods=['POST'])
def send_url_card():
    """发送URL卡片"""
    if not wx:
        return jsonify({"status": "error", "message": "WeChat not connected"}), 503
    
    data = request.json
    who = data.get('who')
    url = data.get('url')
    timeout = data.get('timeout', 30)
    
    if not who or not url:
        return jsonify({"status": "error", "message": "Missing 'who' or 'url'"}), 400
        
    try:
        logger.info(f"Sending URL card to {who}: {url}")
        success = wx.SendUrlCard(url=url, friends=who, timeout=timeout)
        if success:
            return jsonify({"status": "success", "message": "URL card sent"})
        else:
            return jsonify({"status": "error", "message": "Failed to send URL card"}), 500
    except Exception as e:
        logger.error(f"Error sending URL card: {e}")
        return jsonify({"status": "error", "message": str(e)}), 500

@app.route('/api/send_files', methods=['POST'])
def send_files():
    """发送文件"""
    if not wx:
        return jsonify({"status": "error", "message": "WeChat not connected"}), 503
    
    data = request.json
    who = data.get('who')
    file_paths = data.get('file_paths', [])
    
    if not who or not file_paths:
        return jsonify({"status": "error", "message": "Missing 'who' or 'file_paths'"}), 400
        
    try:
        logger.info(f"Sending files to {who}: {file_paths}")
        
        # 支持单个文件路径的兼容性
        if isinstance(file_paths, str):
            file_paths = [file_paths]

        success = wx.SendFiles(file_paths, who)
        if success:
            return jsonify({"status": "success", "message": f"Sent {len(file_paths)} files"})
        else:
            return jsonify({"status": "error", "message": "Failed to send files"}), 500
    except Exception as e:
        logger.error(f"Error sending files: {e}")
        return jsonify({"status": "error", "message": str(e)}), 500


@app.route('/api/resolve_link_url', methods=['POST'])
def resolve_link_url():
    """按需解析链接卡片真实URL。"""
    if not wx:
        return jsonify({"status": "error", "message": "WeChat not connected"}), 503

    data = request.json
    chat_name = data.get('chat_name')
    message_id = data.get('message_id')
    timeout = int(data.get('timeout', 30) or 30)

    if not chat_name or not message_id:
        return jsonify({"status": "error", "message": "Missing 'chat_name' or 'message_id'"}), 400

    try:
        msg = _get_cached_message(chat_name, message_id)
        if msg is None:
            return jsonify({
                "status": "error",
                "message": f"Message not found in cache: {chat_name}:{message_id}"
            }), 404

        logger.info("🔗 按需解析链接卡片URL: %s:%s", chat_name, message_id)
        get_url = getattr(msg, "get_url", None)
        if not callable(get_url):
            return jsonify({
                "status": "error",
                "message": "Current mabowx message object does not support get_url()",
            }), 501
        url = get_url(timeout=timeout)
        if isinstance(url, str) and url.strip().startswith(("http://", "https://")):
            return jsonify({"status": "success", "url": url})
        return jsonify({"status": "error", "message": "Failed to resolve link URL"}), 500
    except Exception as e:
        logger.error(f"Error resolving link URL: {e}", exc_info=True)
        return jsonify({"status": "error", "message": str(e)}), 500


@app.route('/api/download_image_message', methods=['POST'])
def download_image_message():
    """下载指定消息ID的图片消息"""
    if not wx:
        return jsonify({"status": "error", "message": "WeChat not connected"}), 503

    data = request.json
    chat_name = data.get('chat_name')
    message_id = data.get('message_id')

    if not chat_name or not message_id:
        return jsonify({"status": "error", "message": "Missing 'chat_name' or 'message_id'"}), 400

    # 从缓存中获取消息对象
    msg = _get_cached_message(chat_name, message_id)
    if msg is None:
        return jsonify({"status": "error", "message": "Message not found in cache"}), 404

    cache_key = ("image", chat_name, message_id)
    request_id = uuid.uuid4().hex

    def _download_once() -> str:
        logger.info("Downloading image message once: %s:%s type=%s request_id=%s", chat_name, message_id, type(msg), request_id)
        with media_download_trace(msg, request_id=request_id, chat=chat_name, message_id=message_id):
            file_path = msg.download()
        logger.info("Download completed, result: %s", file_path)
        if isinstance(file_path, dict):
            raise RuntimeError(str(file_path.get("message") or file_path))
        normalized_path = str(file_path or "")
        if not normalized_path:
            raise RuntimeError("Download returned no file path")
        if not os.path.exists(normalized_path):
            raise FileNotFoundError(f"Downloaded file does not exist: {normalized_path}")
        _log_image_download_audit("image", chat_name, message_id, normalized_path, msg=msg)
        return normalized_path

    try:
        file_path = media_download_deduplicator.run(
            cache_key,
            _download_once,
            cache_validator=lambda value: os.path.exists(str(value)),
        )
        logger.info("Successfully resolved image download: %s", file_path)
        return jsonify({"status": "success", "file_path": file_path})
    except TimeoutError as e:
        logger.warning("Image download is still in progress: %s:%s", chat_name, message_id)
        response = jsonify({"status": "busy", "message": str(e)})
        response.status_code = 503
        response.headers["Retry-After"] = "5"
        return response
    except MediaFileMismatchError as e:
        get_media_audit = getattr(msg, "get_media_audit", None)
        verification = dict(get_media_audit() if callable(get_media_audit) else {})
        rejected_path = str(verification.get("candidate_path") or "")
        if rejected_path and os.path.isfile(rejected_path):
            _log_image_download_audit(
                "image_rejected",
                chat_name,
                message_id,
                rejected_path,
                msg=msg,
            )
        else:
            logger.warning(
                "图片绑定拒绝: chat=%r message_id=%s reason=%s",
                chat_name,
                message_id,
                e,
            )
        return jsonify({
            "status": "identity_rejected",
            "error_code": "image_identity_mismatch",
            "message": str(e),
        }), 422
    except MediaIdentityError as e:
        logger.warning(
            "图片界面身份暂时失效: chat=%r message_id=%s reason=%s",
            chat_name,
            message_id,
            e,
        )
        response = jsonify({
            "status": "retryable",
            "error_code": "image_ui_identity_changed",
            "message": str(e),
        })
        response.status_code = 503
        response.headers["Retry-After"] = "1"
        return response
    except Exception as e:
        logger.error(
            "图片下载发生未预期错误: chat=%r message_id=%s error=%s request_id=%s",
            chat_name,
            message_id,
            e,
            request_id,
            exc_info=True,
        )
        return jsonify({
            "status": "error",
            "error_code": "image_download_internal_error",
            "message": str(e),
        }), 500






@app.route('/api/get_current_chat', methods=['GET'])
def get_current_chat():
    """获取当前聊天信息"""
    if not wx:
        return jsonify({"status": "error", "message": "WeChat not connected"}), 503
    
    try:
        logger.info("Getting current chat info")
        
        # 获取当前聊天信息
        chat_info = wx.GetCurrentChat()
        if chat_info:
            logger.info(f"Successfully got current chat info: {chat_info}")
            return jsonify({"status": "success", "chat_info": chat_info})
        else:
            return jsonify({"status": "error", "message": "No current chat found"}), 404
            
    except Exception as e:
        logger.error(f"Error getting current chat info: {e}")
        return jsonify({"status": "error", "message": str(e)}), 500

@app.route('/api/keep_running', methods=['POST'])
def keep_running():
    """保持运行"""
    if not wx:
        return jsonify({"status": "error", "message": "WeChat not connected"}), 503
    
    try:
        logger.info("Starting KeepRunning mode")
        wx.KeepRunning()
        return jsonify({"status": "success", "message": "KeepRunning started"})
    except Exception as e:
        logger.error(f"Error starting KeepRunning: {e}")
        return jsonify({"status": "error", "message": str(e)}), 500

@app.route('/live', methods=['GET'])
def liveness_check():
    """纯进程存活检查；不依赖微信、监听器或任何 UI 状态。"""
    return jsonify({
        "status": "ok",
        "service": "wx_bot",
        "service_instance_id": wechat_service_instance_id,
        "timestamp": time.time(),
    })


@app.route('/health', methods=['GET'])
def health_check():
    """返回只读健康快照；轮询接口绝不主动触碰微信 UI。"""
    now = time.time()
    client = wx
    wechat_connected = client is not None
    online_probe = _online_probe_snapshot()
    online_probe["stale"] = bool(
        online_probe.get("age_sec") is None
        or float(online_probe.get("age_sec") or 0) > ONLINE_PROBE_INTERVAL_SEC * 6
    )
    wechat_online = bool(wechat_connected and online_probe.get("online"))

    with desired_listeners_lock:
        desired_snapshot = {name: meta.copy() for name, meta in desired_listeners.items()}

    library_status = client.GetListenerStatus() if client is not None else {}
    listener_payload = _listener_status_payload(desired_snapshot, library_status)

    if not wechat_connected or not wechat_online:
        health_status = "unavailable"
    elif online_probe.get("state") in {"busy", "suspect", "recovering"} or online_probe.get("stale"):
        health_status = "degraded"
    elif listener_payload["status"] in {"degraded", "unknown"}:
        health_status = "degraded"
    else:
        health_status = "ok"

    connection_id = None
    if wechat_connected and wechat_connection_generation > 0:
        connection_id = f"{wechat_service_instance_id}:{wechat_connection_generation}"

    return jsonify({
        "status": "ok",
        "health_status": health_status,
        "wechat_connected": wechat_connected,
        "wechat_online": wechat_online,
        "online_check_skipped": True,
        "online_check_mode": "cached",
        "online_probe": online_probe,
        "service_instance_id": wechat_service_instance_id,
        "connection_generation": wechat_connection_generation,
        "connection_id": connection_id,
        "listeners": listener_payload,
        "timestamp": now,
        "service": "wx_bot"
    })

@app.route('/api/listeners/status', methods=['GET'])
def listeners_status():
    """返回期望监听列表和当前实际监听子窗口列表；不访问微信 UIA。"""
    client = wx
    if client is None:
        return jsonify({
            "status": "error",
            "message": "WeChat not connected",
            "desired": [],
            "actual": [],
            "missing": [],
            "registered": [],
            "window_auto_repair": {},
        }), 503

    try:
        with desired_listeners_lock:
            desired_snapshot = {name: meta.copy() for name, meta in desired_listeners.items()}

        listener_payload = _listener_status_payload(
            desired_snapshot,
            client.GetListenerStatus(),
        )
        return jsonify({
            **listener_payload,
            "listener_status": listener_payload["status"],
            "status": "success",
            "timestamp": time.time(),
        })
    except Exception as e:
        logger.error(f"Error getting listener status: {e}")
        return jsonify({"status": "error", "message": str(e)}), 500

@app.route('/api/is_online', methods=['GET'])
def is_online():
    """返回连接监控线程维护的在线缓存，不创建第二个 UI 探针。"""
    if not wx:
        return jsonify({"status": "error", "message": "WeChat not connected", "online": False}), 503

    online_probe = _online_probe_snapshot()
    return jsonify({
        "status": "success",
        "online": bool(online_probe.get("online")),
        "check_skipped": True,
        "check_mode": "cached",
        "cached_online": bool(online_probe.get("online")),
        "cached_at": online_probe.get("checked_at"),
        "online_probe": online_probe,
        "message": "Online status served from the connection supervisor cache",
    })

def _download_quote_media_on_demand(media_kind: str):
    """按不可变消息 ID 下载引用图片或视频。"""
    if not wx:
        return jsonify({"status": "error", "message": "WeChat not connected"}), 503

    data = request.get_json(silent=True) or {}
    chat_name = data.get('chat_name')
    message_id = data.get('message_id')
    try:
        requested_timeout = int(data.get("timeout") or (120 if media_kind == "video" else 30))
    except (TypeError, ValueError):
        requested_timeout = 120 if media_kind == "video" else 30
    operation_timeout = max(5, min(120, requested_timeout))

    if not chat_name or not message_id:
        return jsonify({"status": "error", "message": "Missing 'chat_name' or 'message_id'"}), 400

    # 从缓存中查找消息对象
    msg = _get_cached_message(chat_name, message_id)
    if msg is None:
        return jsonify({
            "status": "error",
            "message": f"Message not found in cache: {chat_name}:{message_id}"
        }), 404

    cache_key = (f"quote_{media_kind}", chat_name, message_id)

    def _download_quote_once() -> str:
        logger.info("🎬 按需下载引用%s（单次）: %s:%s", media_kind, chat_name, message_id)
        download = getattr(msg, "download_quote_media", None)
        if not callable(download):
            # 兼容重启前创建、仍只有旧方法名的消息对象。
            download = getattr(msg, "download_quote_image", None)
        if not callable(download):
            raise RuntimeError("Current mabowx message does not support quoted media download")
        media_path = download(timeout=operation_timeout)
        normalized_path = str(media_path or "")
        if not normalized_path:
            raise RuntimeError(f"Failed to download quoted {media_kind}")
        if not os.path.exists(normalized_path):
            raise FileNotFoundError(f"Downloaded quoted media does not exist: {normalized_path}")
        _log_image_download_audit(f"quote_{media_kind}", chat_name, message_id, normalized_path, msg=msg)
        return normalized_path

    try:
        media_path = media_download_deduplicator.run(
            cache_key,
            _download_quote_once,
            cache_validator=lambda value: os.path.exists(str(value)),
        )
        logger.info("🎬 引用%s按需下载成功: %s", media_kind, media_path)
        return jsonify({
            "status": "success",
            "file_path": media_path,
            "media_type": media_kind,
            "message": f"Quoted {media_kind} downloaded successfully",
        })
    except TimeoutError as e:
        logger.warning("引用%s下载仍在进行: %s:%s", media_kind, chat_name, message_id)
        response = jsonify({"status": "busy", "message": str(e)})
        response.status_code = 503
        response.headers["Retry-After"] = "5"
        return response
    except Exception as e:
        logger.error("按需下载引用%s失败: %s", media_kind, e)
        return jsonify({"status": "error", "message": str(e)}), 500


@app.route('/api/download_quote_image_on_demand', methods=['POST'])
def download_quote_image_on_demand():
    """按需下载引用图片（保留旧接口）。"""
    return _download_quote_media_on_demand("image")


@app.route('/api/download_quote_video_on_demand', methods=['POST'])
def download_quote_video_on_demand():
    """按需打开微信预览并下载被引用的视频。"""
    return _download_quote_media_on_demand("video")

@app.route('/api/restart_wechat', methods=['POST'])
def restart_wechat():
    """手动重启微信连接"""
    global wx, restart_requested
    try:
        logger.info("🔄 手动重启微信连接请求")
        
        # 设置重启标志
        restart_requested = True
        logger.info("✅ 重启标志已设置，将在下次循环时生效")
        
        # 如果当前微信实例存在，尝试中断KeepRunning
        if wx:
            try:
                # 设置为None，这可能会导致KeepRunning抛出异常从而退出
                wx = None
                logger.info("已标记当前微信实例为关闭状态")
            except Exception as e:
                logger.debug(f"关闭当前微信实例时发生异常: {e}")
        
        return jsonify({
            "status": "success", 
            "message": "微信重启请求已提交，重连将在几秒内开始...",
            "timestamp": time.time()
        })
        
    except Exception as e:
        logger.error(f"手动重启微信连接失败: {e}")
        return jsonify({
            "status": "error", 
            "message": f"重启失败: {str(e)}",
            "timestamp": time.time()
        }), 500

if __name__ == '__main__':
    # 添加启动日志
    logger.info("🚀 微信机器人进程启动")
    logger.info(f"📁 当前工作目录: {os.getcwd()}")
    logger.info(f"📄 日志文件路径: {os.path.abspath('data/wx_bot.log')}")
    
    # 在独立线程中启动微信逻辑
    wechat_thread = threading.Thread(target=start_wechat_logic, daemon=True)
    wechat_thread.start()
    
    # 启动Flask服务器
    # 注意：使用use_reloader=False，因为重载会干扰微信连接
    wx_bot_port = int(os.getenv("WX_BOT_PORT", "5555"))
    logger.info("Starting Flask API server for WeChat Bot on port %s...", wx_bot_port)
    app.run(host='127.0.0.1', port=wx_bot_port, debug=False, use_reloader=False, threaded=True)
